### ISSUE TITLE
java.lang.NullPointerException: Parameter specified as non-null is null: method de.timo_reymann.mjml_support.documentation.MjmlDocumentationProvider.getUrlFor, parameter originalElement

### ISSUE THREAD

**Issue by andreas-becker** [timo-reymann/intellij-mjml-support#99] opened 2021-12-16 09:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Windows 10 10.0 (amd64)
* WSL2
* IDE: IntelliJ IDEA 2021.3 (build IU-213.5744.223)
* Plugin: 1.20.2
* NPM installed v4.11.0 in current project directory

## Problem description
The preview in IntelliJ says "Failed to render mjml using helper script". The "Rendering script" in the "MJML Settings" under "Tools" says, it uses the "Bundled" script with v4.10.2.

## Expected Behavior
The preview should be visible

### Actual Behavior
It shows an error

### Steps to Reproduce
Use IntelliJ, add MJML Plugin create new Project add mjml into it, create new mjml file.

### Important Factoids

The project files are stored inside the WSL2, the IntelliJ Installation is on Windows. 
In IntelliJ, the Settings for NodeJs uses the node-version installed inside WSL2

#### StackTrace
```
java.lang.NullPointerException: Parameter specified as non-null is null: method de.timo_reymann.mjml_support.documentation.MjmlDocumentationProvider.getUrlFor, parameter originalElement
at de.timo_reymann.mjml_support.documentation.MjmlDocumentationProvider.getUrlFor(MjmlDocumentationProvider.kt)
at com.intellij.lang.documentation.CompositeDocumentationProvider.getUrlFor(CompositeDocumentationProvider.java:129)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:60)
at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt:25)
at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt)
at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:65)
at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:12)
at com.intellij.openapi.application.rw.ReadAction$tryReadAction$3.run(ReadAction.kt:74)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
at com.intellij.openapi.application.rw.ReadAction.tryReadAction(ReadAction.kt:71)
at com.intellij.openapi.application.rw.ReadAction.access$tryReadAction(ReadAction.kt:14)
at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2$2.run(ReadAction.kt:62)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2.invokeSuspend(ReadAction.kt:60)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by timo-reymann** [comment] 2021-12-16 10:03
Hi, can you please provide the document that leads to this error?

**Comment by andreas-becker** [comment] 2021-12-17 12:04
Well, it does not even work with a basic one
```
<mjml>
  <mj-head>
    <mj-title>Title of document</mj-title>
    <mj-attributes>
      <mj-all color="#666666" font-family="Arial, sans-serif" font-size="15px" line-height="24px" padding="0" />
      <mj-class name="bg-lightgrey" background-color="#e4e4e4" />
      <mj-class name="bg-white" background-color="#ffffff" />
      <mj-class name="h2" color="#666666" font-size="14px" font-weight="700" line-height="21px" text-transform="uppercase" />
      <mj-divider border-width="1px" border-style="solid" border-color="#e4e4e4" padding-bottom="7px" />
      <mj-section padding="15px" />
      <mj-text padding-bottom="7px" />
    </mj-attributes>
  </mj-head>
  <mj-body mj-class="bg-lightgrey">
    <mj-section mj-class="bg-white">
      <mj-column>
        <mj-text mj-class="h2">Headline</mj-text>
        <mj-text>Lorem ipsum dolor sit...</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by timo-reymann** [comment] 2021-12-17 16:33
Okay thats really strange, i tried it on Linux with the exact same versions and here it renders.
Can you verify this has nothing to do with the WSL e. g. by using node installed on Windows?

![image](https://user-images.githubusercontent.com/21024948/146577238-f3a03b12-e19a-486a-aa68-4762b0d47b49.png)

**Comment by andreas-becker** [comment] 2021-12-20 18:14
Oh, looks like you installed IntelliJ also in the wsl. In our setup, IntelliJ is installed in Windows and using the Project from inside the WSL

**Comment by timo-reymann** [comment] 2021-12-20 20:34
I only use Linux/Mac for development 😅

Can you try to move node out of WSL and see if this works for you? Just to narrow down the possible problems :)

**Comment by timo-reymann** [comment] 2022-01-05 17:29
Since i cant seem to reproduce it and there is no additional information provided i will close this for now.

**Closed by timo-reymann** 2022-01-05 17:29 UTC
Labels: bug, information required
