### ISSUE TITLE
Error when multiple instances of intelliJ are open

### ISSUE THREAD

**Issue by aconde-biocom** [timo-reymann/intellij-mjml-support#34] opened 2021-06-29 19:24 UTC
I get the following error message when there are multiple intelliJ instances open if any of them are mjml projects.
```
java.nio.file.FileSystemException:  C:\Users\aconde\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40.plugins\mjml-support\renderer.zip: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
	at java.base/java.nio.file.Files.copy(Files.java:3130)
	at de.timo_reymann.mjml_support.util.FilePluginUtil.copyFile(FilePluginUtil.kt:18)
	at de.timo_reymann.mjml_support.editor.render.BuiltinRenderResourceProvider.copyResources(BuiltinRenderResourceProvider.kt:22)
	at de.timo_reymann.mjml_support.editor.MjmlPreviewStartupActivity$runActivity$1.run(MjmlPreviewStartupActivity.kt:17)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Thank you for creating this plugin!

**Comment by timo-reymann** [comment] 2021-06-30 15:53
Hello @aconde-biocom,
first thank you for using my plugin the bug report! :)

Next time (hopefully not a bug report) please use the issue templates, they help me get a standardized format.

Alright, i already know where the problem lies, but the fix for it might take some time.

**Comment by timo-reymann** [comment] 2021-07-03 11:26
The fix i have implemented works fine for me, when JetBrains approved the new snapshot i will post the link to the update so you can test it with your setup. If everything also works for you its going to the stable version for the marketplace :)

**Comment by aconde-biocom** [comment] 2021-07-06 16:36
Thank you!

Adam Conde | Sr. Director, Business Systems
Biocom California

**Comment by timo-reymann** [comment] 2021-07-06 19:10
@aconde-biocom can you try it with the snapshot from here: https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot/126182

Just to verify it works :)

**Comment by aconde-biocom** [comment] 2021-07-06 21:47
It looks like the error has been fixed.  However, now I'm getting the error "Failed to render mjml using helper script" when trying to preview an email.  I'm not sure if it's related to your update, but I haven't seen this message before.

**Comment by timo-reymann** [comment] 2021-07-07 06:51
Alright, can you provide me the stack trace (if there is one) and a sample?

**Comment by aconde-biocom** [comment] 2021-07-07 17:09
``Failed to delete lock file.
java.nio.file.FileSystemException: C:\Users\aconde\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7628.21.plugins\mjml-support\renderer.zip.lock: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1142)
	at de.timo_reymann.mjml_support.util.FileLockUtil.runWithLock(FileLockUtil.kt:40)
	at de.timo_reymann.mjml_support.editor.render.BuiltinRenderResourceProvider.copyResources(BuiltinRenderResourceProvider.kt:29)
	at de.timo_reymann.mjml_support.editor.MjmlPreviewStartupActivity$runActivity$1.run(MjmlPreviewStartupActivity.kt:17)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by timo-reymann** [comment] 2021-07-07 17:43
Alright, found it. Deleting the lock-File was not a great idea. Will be fixed with next snapshot, sorry about that.

**Comment by timo-reymann** [comment] 2021-07-08 18:51
New version: https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot/126575

Tested on MacOS and Linux, can you verify it also works for you? :)

**Comment by aconde-biocom** [comment] 2021-07-08 20:23
That seems to have fixed it.  Thank you!

**Closed** 2021-07-09 15:32 UTC
Labels: bug
