### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class de.timo_reymann.mjml_support.lang.MjmlHtmlLanguage

### ISSUE THREAD

**Issue by przemosk** [timo-reymann/intellij-mjml-support#69] opened 2021-09-23 18:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Mac OS X 11.5.2 (x86_64)
* IDE: RubyMine 2021.2.2 (build RM-212.5284.50)
* Plugin: 1.18.0

#### StackTrace
```
java.lang.NoClassDefFoundError: Could not initialize class de.timo_reymann.mjml_support.lang.MjmlHtmlLanguage
at de.timo_reymann.mjml_support.completion.MjmlColorAttributeTypeElementColorProvider.getColorFrom(MjmlColorAttributeTy

**Comment by timo-reymann** [comment] 2021-09-23 18:53
Duplicate of #67

**Closed by timo-reymann** 2021-09-23 18:53 UTC
Labels: duplicate
