### ISSUE TITLE
On re-rendering, position the vertical scrolling "better"

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#51] opened 2021-08-05 03:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Scenario

An email developer is working an email longer than their screen height. In particular, they're working near the bottom of the email. They make a change; a new rendering is necessary.

### Current behavior

The new rendering, on my computer, always shows scrolled up to the top. Developers with this experience must scroll to their preferred position to observe the result of their changes.

If it's going to always default to a single place, that might be the right one. However, it's only a lucky coincidence when that position is the developer's preference. The other times, this positioning pulls them from their development "headspace".

### It'd be nice if ...

The new rendering showed closer to the part of the email the developer is thinking about.

### Candidate places to scroll

[humor attempt] Mathematically, scrolling to the middle of the rendering would provide the lowest average error from the developer's preference. [not a suggestion, but about true; end humor attempt]

Scroll the same distance down from the top as the last position of the preview.

Same as above, but if the last position of the preview is closer to the bottom, scroll the same distance up from the bottom.

Scroll to the place of the most recent edit.

Scroll to match the editor window scroll position. (Perhaps the developer scrolled the editor window since the last edit and would prefer to start there.)

Preferred? I haven't thought about it enough. Maybe the last one, but that's a snap judgment. Anything closer to the developer's preference is better. It's possible to overthink this.

**Comment by timo-reymann** [comment] 2021-08-05 20:25
This would be indeed a nice feature but requires some research/PoC for the following points:
- how to get scroll offset from browser (event to java side?)
- restore scroll  offset inside browser (inject some code into rendered mjml?)

**Comment by GarryFlemings** [comment] 2021-08-06 02:56
Nice-to-have. Not urgent.

**Comment by timo-reymann** [comment] 2021-08-07 08:17
Scroll sync won't make too much sense here since the mjml code and the corresponding height in the html can be very diferent, not like for markdown where it is more to "real positioning".

So the solution would consist of:
- Inject code with [JBCefJSQuery](https://plugins.jetbrains.com/docs/intellij/jcef.html#jbcefjsquery) to track scroll and send back to plugin context
- [window.scroll](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll) for every new rendering of the content to restore the previous scroll height (via JBCefBrowser#executeJavaScript)

This way the newly rendered content will remain at the same scroll position, no matter where the dev is working in the mail.

Things to check/Concerns:
- Scroll could lag a bit (like a stuttering window)

**Comment by timo-reymann** [comment] 2021-08-07 20:26
First implementation is set up. My concern was right that the preview is a bit "stutering" when the page is rendered.
The problem is there is not really a way around it since the entire page is replaced and then the scroll is called that simply costs time

**Comment by timo-reymann** [comment] 2021-08-10 09:35
Alright so it seems there is no way around the little stuttering. I will merge this into master and publish it with the next snapshot after the release

**Comment by timo-reymann** [comment] 2021-08-12 19:46
I will also add a button to toggle the "keep position behaviour" for low end computers.

As 1.17.0 is ready for release, this has been merged into main

**Comment by timo-reymann** [comment] 2021-08-24 16:54
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2021.08.24-405</a>

**Closed** 2021-08-24 16:59 UTC
Labels: enhancement
