### ISSUE TITLE
Preview not including content that's added by mj-include tags

### ISSUE THREAD

**Issue by MiguelKorn** [timo-reymann/intellij-mjml-support#131] opened 2022-08-15 12:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Linux
* IDE: Webstorm 2022.2 (222.3345.108)

## Problem description

As the title says, when including files with the `mj-include` tag, the included content is not visible in the html/visual preview. I used this same mjml with import tag within vscode and this [mjml plugin](https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml) to check if i made a mistake, but it shows the included content. So it looks like there is something going wrong displaying included content.

**Comment by timo-reymann** [comment] 2022-08-19 11:58
Hey @MiguelKorn,

thanks for reporting. Currently on vacation but i will try to reproduce and fix it around next week when i am back.

Could you maybe provide a small demo project or project structure? This would make it a lot easier to troubleshoot :)

**Comment by timo-reymann** [comment] 2022-09-18 10:41
I am still unable to reproduce it. Since no demo/project structure was provided, i will close this for now.

**Closed by timo-reymann** 2022-09-18 10:41 UTC
Labels: bug
